@startuml
'https://plantuml.com/class-diagram

class ToDo{
    main()
    start()
    createList()
    openNewList()
    viewList()
    goBack()
    selectList()
    dueDate()
}

class ToDo_Controller{
    editDate()
    editDescription()


}

javafx.Application <|-- ToDo

ToDo -- ToDo_Controller
@enduml