@startuml
'https://plantuml.com/class-diagram

class ToDo{
    + main (args : String[]) : void
    + start (stage : Stage) : void
}

class ToDoController{
    + getTask () : String
    + setTask (task : String) : void
    + getTaskDescription () : String
    + setTaskDescription (taskDescription : String) : void
    + isCompletion () : boolean
    + getTaskDate () : String
    + addButtonClicked ()
    - root : Parent
    - scene : Scene
    - stage : Stage
    + pane : Pane
    --
    + switchToToDoScene (event : ActionEvent) : void
    + switchToAllListScene (event : ActionEvent) : void
    + switchToSettings (event : ActionEvent) : void
    + switchToAbout (event : ActionEvent) : void
    + sceneButtonClicked1 (actionEvent : ActionEvent) : void
    + sceneButtonClicked2 (actionEvent : ActionEvent) : void
    + sceneButtonClicked3 (actionEvent : ActionEvent) : void
    + sceneButtonClicked4 (actionEvent : ActionEvent) : void
}

javafx.Application <|-- ToDo

ToDo -- ToDoController
@enduml